config/routes.rb
Rails.application.routes.draw do
  root 'portal#index'

  resources :users, only: [:new, :create, :show, :edit, :update]
  resources :sessions, only: [:new, :create, :destroy]
  resources :teams, only: [:new, :create, :show, :edit, :update, :index]
  resources :requirements, only: [:new, :create, :show, :edit, :update, :index]
  resources :calendar, only: [:show]

  get '/signin' => 'sessions#new'
  get '/signup' => 'users#new'
  delete '/signout' => 'sessions#destroy'

  get '/teams/:id/invite' => 'teams#invite'
  get '/invite_member' => 'teams#invite_member'
  get '/accept_invite' => 'teams#accept_invite'
  get '/refuse_invite' => 'teams#refuse_invite'
  get '/myteams' => 'teams#myteams'
  get '/teams/:id/team_requirements' => 'teams#team_requirements'
  get '/teams/:id/wiki' => 'teams#wiki'
  get '/teams/:id/wiki/edit' => 'teams#edit_wiki'

  get '/invites' => 'invites#index'

  get '*unmatched_route', :to => 'application#raise_not_found!'

  get '/requirements/:id' => 'requirements#show'
  get '/user_story' => 'requirements#edit'

  get 'calendar#show' => 'calendar#show'

end

app/models/invite.rb
# File: invite.rb.
# Purpose: The invite model.
# License: GPL v3.
# Sioha Group.
# FGA - UnB Faculdade de Engenharias do Gama - Universidade de Brasília.

class Invite < ActiveRecord::Base
  belongs_to :user
  belongs_to :team
end

app/controllers/invites_controller.rb
# File: invites_controller.rb.
# Purpose: Map actions relative to invite model
# License: GPL v3.
# Sioha Group.
# FGA - UnB Faculdade de Engenharias do Gama - Universidade de Brasília.

class InvitesController < ApplicationController
# checks if the user is logged in sistem  
  before_action :require_login

# action that renders the index page of the invites controller
  def index
    @all_invites = Invite.where(user: current_user)
    @accepted_invites = @all_invites.where(accepted: true)
    @pending_invites = @all_invites.where(pending: true)
    @invites = @pending_invites
  end

end

app/views/invites/_pending_invites.html.erb
<% unless @invites.empty? %>
  <center><h1>Convites Pendentes</h1></center>
  <table class="table table-hover index-table-pending">
    <thead>
      <tr>
        <td>Time</td>
        <td>Dono</td>
        <td>Descrição</td>
        <td>Aceitar</td>
        <td>Recusar</td>
      </tr>
    </thead>

    <tbody>
      <% @invites.each do |i| %>
        <tr>
          <td><%= link_to "#{i.team.name}", i.team %></td>
          <td><%= link_to "#{i.team.user.name}", i.team.user %></td>
          <td><%= i.team.description %></td>
          <td><%= link_to '', accept_invite_path(id: current_user.id, invite_id: i.id), class: "btn btn-success glyphicon glyphicon-ok" %></td>
          <td><%= link_to '', refuse_invite_path(id: current_user.id, invite_id: i.id), class: "btn btn-danger glyphicon glyphicon-remove" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/invites/index.html.erb
<div class='invites-index-page'>
  <h1>Ultimos convites aceitos:</h1>
  <table class='table'>
    <thead>
      <tr>
        

<div class='row'> 

<div class='col-md-4 time'>   
<td>Time</td>
<td>Dono do time</td>
      </tr>
  </div> 

    </thead>
    <tbody>
      <% @accepted_invites.each do |ai| %>
        <% if ai.team %>
          <tr>
            <td><%= link_to ai.team.name, ai.team %></td>
            <td><%= link_to ai.team.user.name, ai.team.user %></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>

  <h1>Convites pendentes:</h1>
  <%= render 'invites/pending_invites' %>
</div>