config/routes.rb
Rails.application.routes.draw do
  root 'portal#index'

  resources :users, only: [:new, :create, :show, :edit, :update]
  resources :sessions, only: [:new, :create, :destroy]
  resources :teams, only: [:new, :create, :show, :edit, :update, :index]
  resources :requirements, only: [:new, :create, :show, :edit, :update, :index]
  resources :calendar, only: [:show]

  get '/signin' => 'sessions#new'
  get '/signup' => 'users#new'
  delete '/signout' => 'sessions#destroy'

  get '/teams/:id/invite' => 'teams#invite'
  get '/invite_member' => 'teams#invite_member'
  get '/accept_invite' => 'teams#accept_invite'
  get '/refuse_invite' => 'teams#refuse_invite'
  get '/myteams' => 'teams#myteams'
  get '/teams/:id/team_requirements' => 'teams#team_requirements'
  get '/teams/:id/wiki' => 'teams#wiki'
  get '/teams/:id/wiki/edit' => 'teams#edit_wiki'

  get '/invites' => 'invites#index'

  get '*unmatched_route', :to => 'application#raise_not_found!'

  get '/requirements/:id' => 'requirements#show'
  get '/user_story' => 'requirements#edit'

  get 'calendar#show' => 'calendar#show'

end

app/controllers/calendar_controller.rb
class CalendarController < ApplicationController
# this method allows the calendar to show the date updated
  def show
    @date = params[:date] ? Date.parse(params[:date]) : Date.today
  end
end

app/helpers/calendar_helper.rb
module CalendarHelper
  def calendar(date = Date.today, &block)
    Calendar.new(self, date, block).table
  end
end

app/views/calendar/show.html.erb
<div class="row">
  <div class="col-md-12 text-center">
    <div class="well controls">
      <%= link_to calendar_path(date: @date - 1.month), class: "btn btn-default" do %>
        <i class="glyphicon glyphicon-backward"></i>
      <% end %>
      <%= "#{@date.strftime("%B")} #{@date.year}" %>
      <%= link_to calendar_path(date: @date + 1.month), class: "btn btn-default" do %>
        <i class="glyphicon glyphicon-forward"></i>
      <% end %>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <%= calendar @date do |date| %>
      <%= date.day %>  
    <% end %>
  </div>
</div>