config/routes.rb
Rails.application.routes.draw do
  root 'portal#index'

  resources :users, only: [:new, :create, :show, :edit, :update]
  resources :sessions, only: [:new, :create, :destroy]
  resources :teams, only: [:new, :create, :show, :edit, :update, :index]
  resources :requirements, only: [:new, :create, :show, :edit, :update, :index]
  resources :calendar, only: [:show]

  get '/signin' => 'sessions#new'
  get '/signup' => 'users#new'
  delete '/signout' => 'sessions#destroy'

  get '/teams/:id/invite' => 'teams#invite'
  get '/invite_member' => 'teams#invite_member'
  get '/accept_invite' => 'teams#accept_invite'
  get '/refuse_invite' => 'teams#refuse_invite'
  get '/myteams' => 'teams#myteams'
  get '/teams/:id/team_requirements' => 'teams#team_requirements'
  get '/teams/:id/wiki' => 'teams#wiki'
  get '/teams/:id/wiki/edit' => 'teams#edit_wiki'

  get '/invites' => 'invites#index'

  get '*unmatched_route', :to => 'application#raise_not_found!'

  get '/requirements/:id' => 'requirements#show'
  get '/user_story' => 'requirements#edit'

  get 'calendar#show' => 'calendar#show'

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id='error_explanation'>
    <div class='alert alert-danger'>
      The form contains <%= pluralize(object.errors.count, 'error') %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class='footer'>
  <div class='container'>
    <div class='row'>

      <div class='col-md-3'>
        <%= image_tag('logo.png', width: 160, height: 110) %>

        <a class='footer-logo', href='/', id='logo'>SIOHA</a>
      </div>

      <div class='col-md-4'>
        <nav>
          <ul>
            <% if signed_in? %>
              <li class='attention-footer'>Navegação</li>
              <li><%= link_to 'Sobre', '#' %></li>
              <li><%= link_to 'Ajuda', '#' %></li>
              <li><%= link_to 'Contribua!', '#' %></li>
              <li><%= link_to 'FAQ', '#' %></li>
              <li><%= link_to "#{current_user.name}", current_user %></li>
              <li><%= link_to 'Deslogar', signout_path, method: :delete %></li>
            <% else %>
              <li class='attention-footer'>Navegação</li>
              <li><%= link_to 'Sobre', '#' %></li>
              <li><%= link_to 'Ajuda', '#' %></li>
              <li><%= link_to 'Contribua!', '#' %></li>
              <li><%= link_to 'FAQ', '#' %></li>
              <li><%= link_to 'Registrar', signup_path %></li>
              <li><%= link_to 'Logar', signin_path %></li>
            <% end %>
          </ul>
        </nav>
      </div>

      <div class="col-md-4">
        <nav>
          <ul>
            <li class='attention-footer'>Informações</li>
            <li><%= link_to 'Outros', '#' %></li>
            <li><%= link_to 'Times', '#' %></li>
            <li><%= link_to 'Estatísticas', '#' %></li>
            <li><%= link_to 'Convites', '#' %></li>
            <li><%= link_to 'Feed', '#' %></li>
            <li><%= link_to 'Sprints', '#' %></li>
            <li><%= link_to 'Backlogs', '#' %></li>
          </ul>
        </nav>
      </div>

      <div class='col-md-1'>
        <%= link_to "", 'https://twitter.com/ProjectSioha', class: "fa fa-twitter footer-twitter" %>
        <%= link_to "", 'https://www.facebook.com/projectsioha', class: "fa fa-facebook footer-facebook" %>
      </div>

    </div>
  </div>
</nav>

</footer>

app/views/shared/_header.html.erb
<nav class='navbar navbar-default'>
  <div class='navbar-header'>
    <a class='navbar-brand' href='/', id='logo'>SIOHA</a>
  </div>

  <ul class='nav navbar-nav navbar-left'>
    <li><%= link_to 'Lista de Times', teams_path %></li>
    <% if signed_in? %>
      <li><%= link_to 'Seus Times', myteams_path %></li>
      <li><%= link_to 'Seus Convites', invites_path %></li>
    <% end %>
  </ul>

  <ul class='nav navbar-nav navbar-right'>
    <% if signed_in? %>
      <li><%= link_to "#{current_user.name}", current_user %></li>
      <li><%= link_to 'Deslogar', signout_path, method: :delete %></li>
    <% else %>
      <li><%= link_to 'Registrar', signup_path %></li>
      <li><%= link_to 'Logar', signin_path %></li>
    <% end %>
  </ul>
</nav>

app/views/shared/_team.html.erb
<div class='team-shared-block'>
  <div class='col-md-4 teams-photo'>
    <% if t.picture? %>
      <%= image_tag t.picture.url, size: "150x100" %>
    <% else %>
      <%= image_tag t.gravatar_url, size: "80x80" %>
    <% end %>
  </div>

  <div class='col-md-4'>
    <h2><%= link_to "#{t.name}", t %></h2>
    <h4><%= t.description %></h4>
    <h3>Owner: <%= link_to "#{t.user.name}", t.user %></h3>
  </div>

  <div class='col-md-4'>
    <% if t.public_to_members %>
      <h3 class='team-public'>Aberto</h3>
    <% else %>
      <h3 class='team-private'>Privado</h3>
    <% end %>
    <% if t.methodology == "Scrum" %>
      <h3 class='methodology-scrum'><%= t.methodology %></h3>
    <% elsif t.methodology == "SAFe" %>
      <h3 class='methodology-safe'><%= t.methodology %></h3>
    <% else %>
      <h3 class='methodology-empty'><%= "Metodologia não definida." %></h3>
    <% end %>
  </div>
</div>

app/views/shared/_team_header.html.erb
<nav class='navbar.navbar-default.team-header'>
  <div class='navbar-header.team-header'>
    <%= link_to t.name, t, class: 'navbar-brand', id: 'team-logo' %>
  </div>

  <ul class='nav navbar-nav navbar-left'>
    <li><%= link_to "Requisitos", '/teams/'+t.id.to_s+'/team_requirements' %></li>
    <li><%= link_to "Wiki", '#' %></li>
    <li><%= link_to "Teste", '', class: "team-info", id: "#{t.id}" %></li>
  </ul>

  <ul class='nav navbar-nav navbar-right'>
  </ul>
</nav>

app/views/shared/_team_index.html.erb
<div class='team-index-show-block'>
  <div class="container">
    <div class="row-fluid">
      <div class="col-md-4">
        <% if t.picture? %>
          <%= image_tag t.picture.url, size: "300x250" %>
        <% else %>
          <%= image_tag t.gravatar_url, size: "300x250" %>
        <% end %>
      </div>

      <div class="col-md-8">
        <h1 class="team-index-show-block-h1"><%= t.name %></h1>
        <h4><%= t.description %></h4>
      </div>
    </div>
  </div>

  <div class="row">
    <div class='col-md-6'>
      <!-- membros -->
      <h1>Membros (<%= @members.count+1 %>)</h1>
      <% if t.user.picture? %>
        <%= link_to (image_tag t.user.picture.url, style: "border: 3px solid red;"), t.user, title: "Admin" %>
      <% else %>
        <%= link_to (image_tag t.user.gravatar_url, style: "border: 3px solid red;"), t.user, title: "Admin" %>
      <% end %>
      <% @members.each do |w| %>
        <% if w.picture? %>
          <%= link_to (image_tag w.picture.url, style: "border: 3px solid red;"), w, title: "Admin" %>
        <% else %>
        <%= link_to (image_tag w.gravatar_url, style: "border: 3px solid red;"), w, title: "Admin" %>
        <% end %>
      <% end %>
    </div>

    <!-- infos -->
    <div class='col-md-6'>
      <% if t.public_to_members %>
        <h3 class='team-public'>Aberto</h3>
      <% else %>
        <h3 class='team-private'>Privado</h3>
      <% end %>
      <% if t.methodology == "Scrum" %>
        <h3 class='methodology-scrum'><%= t.methodology %></h3>
      <% elsif t.methodology == "SAFe" %>
        <h3 class='methodology-safe'><%= t.methodology %></h3>
      <% else %>
        <h3 class='methodology-empty'><%= "Metodologia não definida." %></h3>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_user.html.erb
<div class='col-md-3'>
  <% if t.picture? %>
    <%= image_tag t.picture.url, size: 80 %>
  <% else %>
    <%= image_tag t.gravatar_url, size: 80 %>
  <% end %>
</div>
<div class='col-md-9'>
  <h2><%= link_to "#{t.name}", t %></h2>
  <% if t.public_email %>
    <h3><%= t.email %></h3>
  <% end %>
</div>